Direction/urls.py
from django.urls import path, include
from . import views

app_name = 'Direct'

urlpatterns = [
    path('', views.home, name = 'Home'),
]

Portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('home/', include('Direction.urls', namespace='Home')),
    path('user/', include('users.urls')),
    path('admin', admin.site.urls),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.login, name = 'Login'),
    path('register', views.register, name = 'Register'),
    path('edit', views.edit, name = 'Edit Profile'),
    
]

Direction/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from Portal.settings import BASE_DIR
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.hashers import make_password


def directory(instance, filename):
    return 'posts/{}/{}.'.format(instance.author.username, filename)

class User(models.Model):
    username = models.CharField(max_length=25)
    password = models.CharField(max_length=100)
    title = models.CharField(blank=True, max_length=5)
    firstname = models.CharField(blank=True, max_length=30)
    lastname = models.CharField(blank=True, max_length=30)
    email = models.EmailField(blank=True, max_length=254)
    phone = models.CharField(blank=True, max_length=10)
    
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.password = make_password(self.password)
            
    def __str__(self):
        return self.username
    
    def delete(self,*args, **kwargs):
        posts = Post.objects.filter(author=User.objects.filter(username=self.username))
        for post in posts:
            post.delete()
        super().delete(*args, **kwargs)

class Post(models.Model):
    title = models.CharField(max_length=100)
    thumbnail = models.ImageField(upload_to=directory)
    description = models.TextField()
    dateposted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User , on_delete= models.CASCADE)
    
    def __str__(self):
        return self.title
    
    def delete(self, *args, **kwargs):
        self.thumbnail.delete(save = False)
        super().delete(*args, **kwargs)

users/forms.py
from .models import User, Post
from django.db import models
from django import forms

        
        
class SignUpForm(forms.Form):
    username = forms.CharField(max_length=25)
    password_1 = forms.CharField(max_length=20,widget=forms.PasswordInput )
    password_2 = forms.CharField(max_length=20,widget=forms.PasswordInput )
        
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        

class LoginForm(forms.Form):
    username = forms.CharField(max_length=25)
    password = forms.CharField(max_length=20,widget=forms.PasswordInput )

Direction/views.py
from django.shortcuts import render
from users.models import Post
# Create your views here.
def home(request):
    return render(request,'home.html', { 'title': 'Home','posts': Post.objects.all() } )

users/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.models import User
from .forms import SignUpForm, LoginForm
from .models import User as Client

# # Create your views here.
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST or None)
        if form.is_valid():
            u = form.cleaned_data['username']
            try:
                user = Client.objects.get(username=u)
            except:
                return render(request, 'login.html', {'status_message': 'User does not exist', 'status_code': 0})
            
            if check_password(form.cleaned_data['password'], user.password):
                return HttpResponse('logged in')
            return render(request, 'login.html', {'status_message': 'Invalid Credentials', 'status_code': 0})
    return render(request, 'login.html',{'title': 'Login'})


def logout(request):
    pass

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            client = Client.objects.filter(username=username)
            if len(client) == 0:
                password1 = form.cleaned_data['password_1']
                password2 = form.cleaned_data['password_2']
                if password1 == password2:
                    p = make_password(password1)
                    Client.objects.create(username = username, password = p ).save()
                    return HttpResponse('user created successfully')
                return HttpResponse('password do not match')
            return HttpResponse('user exist')
        return HttpResponse('form not valid')
    return render(request, 'register.html',{'title': 'Register'})

def edit(request):
    return render(request, 'EditProfile.html',{'title': 'Profile Edit'})

templates/EditProfile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container text-center profile profile-view" id="profile" style="margin-bottom: 0px;width: 100%;">
    <div class="row">
        <div class="col-md-12 alert-col relative">
            <div class="alert alert-info absolue center" role="alert"><button type="button" class="close"
                    data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><span>Profile save
                    with success</span></div>
        </div>
    </div>
    <form class="form-inline text-center"
        style="width: 100%;height: 50%;margin-top: 2em;padding-top: 10px;margin-left: 11%;">
        <div class="form-row profile-row">
            <div class="col-md-4 relative">
                <div class="text-center avatar">
                    <div class="d-flex flex-shrink-1 justify-content-center align-items-center align-content-center flex-wrap avatar-bg center"
                        data-bs-hover-animate="pulse"
                        style="margin-bottom: 10px;background-image: url(&quot;{% static 'assets/img/chuttersnap-Zf64Osndqvc-unsplash.jpg'%}&quot;);background-position: center;background-size: cover;background-repeat: no-repeat;">
                        <div class="jumbotron text-center border rounded-circle"
                            style="width: 100%;height: 100%;margin: 0px;opacity: 0.40;color: rgb(34,35,35);"></div>
                    </div>
                </div><input type="file" id="file-input" class="form-control" name="profile_picture"
                    style="background-color: #cccccc;width: 104px;height: 37px;padding-left: 0px;padding-right: 0px;"
                    accept="image/*">
            </div>
            <div class="col-md-8">
                <h1>Edit Profile <i class="fa fa-edit"></i></h1>
                <hr>
                <div class="form-row" style="padding-top: 10px;">
                    <div class="col-sm-12 col-md-6">
                        <div class="form-group" style="padding-right: 10px;"><label>Firstname </label><input
                                class="form-control" type="text" name="firstname" placeholder="Example: John"
                                autocomplete="on" autofocus="" style="width: 238px;"></div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <div class="form-group" style="margin-left: 11px;"><label>Lastname </label><input
                                class="form-control" type="text" name="lastname" placeholder="Example: William"
                                autocomplete="on" style="width: 232px;"></div>
                    </div>
                </div>
                <div class="form-row" style="padding-top: 10px;">
                    <div class="col-sm-12 col-md-6">
                        <div class="form-group" style="padding-right: 10px;"><label>Email</label><input
                                class="form-control" type="email" name="email" placeholder="Company@example.com"
                                autocomplete="on" inputmode="email" style="width: 238px;"></div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <div class="form-group" style="margin-left: 11px;"><label>Phone Number</label><input
                                class="form-control" type="tel" placeholder="Example: +91 - 123456789" autocomplete="on"
                                style="width: 232px;"></div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-12 text-center d-flex d-lg-flex flex-row flex-grow-0 align-items-center flex-wrap justify-content-lg-center align-items-lg-center content-right"
                        style="margin-top: 40px;padding-left: 0px;"><button
                            class="btn btn-primary text-center d-lg-flex justify-content-lg-center align-items-lg-center form-btn"
                            type="submit" style="margin: 0;margin-right: 5%;margin-left: 0;">SAVE </button><button
                            class="btn btn-danger text-center form-btn" type="reset"
                            style="margin: 0;margin-left: 5px;">CANCEL </button>
                        </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Register</title>
    {% endif %}
    <link rel="icon" href="{% static 'assets/img/icon.ico' %}" sizes="16x16">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Serif">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css">

    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/Registration-Form-with-Photo.css'%}">
    <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css'%}">

    <link rel="stylesheet" href="{% static 'assets/css/Profile-Edit-Form.css'%}">

    <style>
        #footer {
            position: absolute;
            height: 50px;
            left: 0px;
            right: 0px;
            margin-top: 20px;
            margin-bottom: 0px;
        }

    </style>
</head>

<body style="font-family: 'Noto Serif', serif;background-color: #cccccc;">
    <nav class="navbar navbar-light navbar-expand-md sticky-top" style="background-color: #2c3531;">
        <div class="container">
            <div><i class="fa fa-book" style="color: rgba(255,255,255,0.9);font-size: 24px;margin-right: 10px;"></i><a
                    class="navbar-brand" href="{% url 'Direct:Home' %}"
                    style="color: rgba(255,255,255,0.9);font-size: 25px;font-family: 'Noto Serif', serif;font-weight: bold;"><em>Hook
                        to Book</em></a></div>
            <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"
                style="background-color: #cccccc;"><span class="sr-only">Toggle navigation</span><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link active nav_small"
                            href="{% url 'Direct:Home' %}"
                            style="color: rgba(255,255,255,0.9);font-size: 18px;font-family: 'Noto Serif', serif;background-color: #37434d;margin-right: 20px;">Home</a>
                    </li>
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"><a class="nav-link nav_small"
                            href="{% url 'users:Register' %}"
                            style="color: rgba(255,255,255,0.9);font-size: 18px;font-family: 'Noto Serif', serif;margin-right: 20px;">Register</a>
                    </li>
                    <li class="nav-item" role="presentation"><a class="nav-link nav_small"
                            href="{% url 'users:Login' %}"
                            style="color: rgba(255,255,255,0.9);font-family: 'Noto Serif', serif;font-size: 18px;">Login</a>
                    </li>
                    <!-- <li class="nav-item" role="presentation"><a class="nav-link nav_small"
                            href="{% url 'users:Edit Profile' %}"
                            style="color: rgba(255,255,255,0.9);font-family: 'Noto Serif', serif;font-size: 18px;">Edit Profile</a>
                    </li> -->
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock content%}
    <footer id="footer" class="footerOmolds">
        <div class="col-auto text-center float-none align-self-end mx-auto visible"
            style="height: 80px;margin-top: 5px;background-color: #2c3532;">
            <p style="color: rgba(255,255,255,0.9);padding-top: 10px;">Made with ♥ for all the book lovers&nbsp;<br>A
                work by
                Achyut Shukla</p>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox-plus-jquery.min.js"></script>
    <script src="{% static 'assets/js/jquery.min.js'%}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'assets/js/bs-init.js'%}"></script>

    <script src="{% static 'assets/js/Profile-Edit-Form.js'%}"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="text-center"
    style="padding: 40px;background-image: url(&quot;{% static 'assets/img/alfons-morales-YLSwjSy7stw-unsplash.jpg' %}&quot;);">
    <div id="jumbo-container">
        <div class="jumbotron border rounded" style="opacity: 0.80;background-color: rgb(21,25,30);">
            <h1 style="color: rgb(255,255,255);font-size: 45px;line-height: 65px;letter-spacing: 1px;">Grab a book to
                unleash the best of you.</h1>
            <p style="color: rgb(255,255,255);font-size: 20px;line-height: 30px;">Nullam id dolor id nibh ultricies
                vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
            <p><a class="btn btn-primary text-center bg-dark" role="button" style="color: rgb(255,255,255);">Learn
                    more</a></p>
        </div>
    </div>
</div>
<div class="container-fluid text-center" style="margin: 10px;margin-right: 0;">
    <h1 style="margin: 5px;padding: 5px;line-height: 24px;letter-spacing: 5px;margin-top: 30px;">Introduction</h1>
    <p class="text-break" style="margin: 5px;padding: 5px;">
        <br>Lorem&nbsp;ipsum,&nbsp;dolor&nbsp;sit&nbsp;amet&nbsp;consectetur&nbsp;adipisicing&nbsp;elit.&nbsp;Sapiente&nbsp;enim&nbsp;ad,&nbsp;eum&nbsp;aut&nbsp;consequatur&nbsp;facilis&nbsp;voluptatibus.Rem&nbsp;repellendus&nbsp;nesciunt&nbsp;sequi&nbsp;maxime&nbsp;voluptates&nbsp;possimus&nbsp;a,&nbsp;saepe&nbsp;cumque&nbsp;consequuntur&nbsp;omnis&nbsp;veniam&nbsp;minus&nbsp;ipsam!&nbsp;Sed&nbsp;adlaudantium,&nbsp;magnam&nbsp;culpa&nbsp;magni&nbsp;sequi&nbsp;animi&nbsp;laborum&nbsp;ut&nbsp;fugiat&nbsp;porro&nbsp;vel&nbsp;explicabo&nbsp;placeat&nbsp;laboriosam&nbsp;quia&nbsp;quamconsequuntur&nbsp;doloremque,&nbsp;enim&nbsp;maiores&nbsp;nemo,&nbsp;perspiciatis&nbsp;labore&nbsp;quod&nbsp;est&nbsp;illum?&nbsp;Voluptas&nbsp;repellendus&nbsp;aliquam,&nbsp;liberoperspiciatis&nbsp;at&nbsp;sint&nbsp;quae&nbsp;iste.&nbsp;Eos&nbsp;omnis&nbsp;quia&nbsp;velit&nbsp;voluptatem.&nbsp;Iure&nbsp;non&nbsp;ratione&nbsp;minus&nbsp;nesciunt&nbsp;expedita.&nbsp;Eligendiquisquam&nbsp;ad&nbsp;minus&nbsp;labore&nbsp;facilis&nbsp;inventore&nbsp;quo,&nbsp;ratione&nbsp;ut&nbsp;voluptates&nbsp;accusantium&nbsp;beatae,&nbsp;quam&nbsp;corporis!&nbsp;Asperioresincidunt&nbsp;aliquid&nbsp;quas&nbsp;distinctio&nbsp;sapiente!<br><br>
    </p>
</div>


<div class="container-fluid text-center" style="margin: 10px;">
    <h1 style="margin: 5px;padding: 5px;line-height: 24px;letter-spacing: 5px;margin-bottom: 5px;">Images</h1>

    <div class="row justify-content-center align-items-center"
        style="margin: 10px;margin-right: 0px;margin-left: 0px;margin-top: 10px;margin-bottom: 0px;padding: 0px;padding-top: 0px;padding-left: 5px;padding-right: 5px;">
        {% for post in posts %}


        <div class="col-auto col-sm-10 col-md-4 col-lg-4 col-xl-4" style="margin-top: 10px;padding-top: 5px;">
            <div class="card">
                <a class="stretched-link text-center" data-lightbox="LibImage" data-title="Image Caption"
                    href="{{ post.thumbnail.url  }}" target="_blank">
                    <img class="card-img-top w-100 d-block" src="{{ post.thumbnail.url  }}" />

                </a>
                <div class="card-body" style="padding: 0px;">
                    <h2 class="text-center card-title" style="margin-bottom: 5px;">{{ post.title }}</h2>
                    <p class="text-center card-text">{{ post.description }}</p>
                </div>
            </div>
            <div class="row justify-content-center align-items-center" style="margin-right: 0px;margin-top: 10px;">
                <div
                    class="col d-flex d-md-flex d-lg-flex d-xl-flex flex-row flex-grow-1 flex-shrink-1 flex-fill justify-content-center align-items-center align-self-center flex-nowrap m-auto justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center">
                    <a href="#"><i class="fa fa-heart-o"
                            style="font-size: 32px;width: 32;height: 31;color: rgb(0,0,0);"></i></a><label
                        style="margin-left: 5px;padding-left: 5px;font-size: 20px;">250</label>
                    <div role="group" class="btn-group" style="padding: 5px;margin: 5px;"><button
                            class="btn text-center flex-column flex-grow-1 flex-shrink-1 flex-fill justify-content-center align-items-center align-content-center flex-nowrap m-auto"
                            type="button" style="width: 100%;height: 100%;"></button></div>
                    <div class="d-lg-flex flex-row justify-content-lg-center avatar-bg center"
                        style="width: 50px;height: 26px;margin-left: 0px;margin-right: 0px;background-position: center;background-repeat: no-repeat;">
                    </div><a class="stretched-link text-body d-lg-flex justify-content-lg-center align-items-lg-center"
                        href="#" target="_blank" style="width: 100%;"><label
                            class="d-lg-flex justify-content-lg-start align-items-lg-center"
                            style="font-size: 20px;margin-left: 5px;padding-left: 0px;" for="username">{{ post.author.username }}</label></a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="register-photo" style="background-color: #cccccc;">
    <div class="form-container">
        <div class="image-holder"></div>
        <form action="login" method="POST" >
            {% csrf_token %}
            <h2 class="text-center"><strong>Log</strong> in.</h2>
            <div class="form-group"><input class="form-control" type="text" name="username" placeholder="Username" autofocus>
            </div>
            <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <!-- <div class="form-group"><input class="form-control" type="password" name="password-repeat"
                    placeholder="Password (repeat)"></div> -->
            <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Sign Up</button></div><a
                class="already" href="{% url 'users:Register' %}">Don't have an account yet? Register now.</a>

            {% if status_message %}
                {% if status_code == 0 %}
                <div role="alert" class="alert alert-danger text-center shadow"
                    style="margin: 4px;padding: 0px;padding-left: 0px; width:100%"><button type="button" class="close"
                        data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">×</span></button><span><strong>{{ status_message }}</strong></span></div>
                {% else %}
                    <div role="alert" class="alert alert-success text-center shadow"
                    style="margin: 4px;padding: 0px;padding-left: 0px; width:100%"><button type="button" class="close"
                        data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">×</span></button><span><strong>{{ status_message }}</strong></span></div>
                {% endif %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock content %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="register-photo" style="background-color: #cccccc;">
    <div class="form-container">
        <div class="image-holder"></div>
        <form method="POST">
            {% csrf_token %}
            <h2 class="text-center"><strong>Create</strong> an account.</h2>
            <div class="form-group">
                <input class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password_1" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password_2" placeholder="Password (repeat)">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Sign Up</button>
            </div><a class="already" href="{% url 'users:Login' %}">You already have an account? Login here.</a>
            {% if status_message %}
            <div role="alert" class="alert alert-danger text-center shadow"
                style="margin: 4px;padding: 0px;padding-left: 0px;"><button type="button" class="close"
                    data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">×</span></button><span><strong>{{ status_message }}</strong></span></div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock content %}